
```{r}
library(tidyverse)
```

```{r}
gamelogs <- read_csv("https://dwillis.github.io/sports-data-files/wbblogs24.csv")
```

```{r}

teamquality <- gamelogs |> 
  select(Conference, Team, TeamFGPCT, TeamTotalRebounds, OpponentFGPCT, OpponentTotalRebounds)

```

```{r}

teamtotals <- teamquality |> 
  filter(!is.na(OpponentFGPCT)) |>
  group_by(Conference, Team) |> 
  summarise(
    FGAvg = mean(TeamFGPCT), 
    ReboundAvg = mean(TeamTotalRebounds), 
    OppFGAvg = mean(OpponentFGPCT),
    OffRebAvg = mean(OpponentTotalRebounds)
    ) 

```



scale function gives us a between 1 and 0 value to help calculate our average. We have to make sure that the z-score is a number. We multiply the opponent's stats by -1 to denote that they are "worse" compared to our values. 

Z-scores are to help compare specific metrics.

```{r}

teamzscore <- teamtotals |> 
  mutate(
    FGzscore = as.numeric(scale(FGAvg, center = TRUE, scale = TRUE)), 
    RebZscore = as.numeric(scale(ReboundAvg, center = TRUE, scale = TRUE)),
    OppZscore = as.numeric(scale(OppFGAvg, center = TRUE, scale = TRUE)) * -1,
    OppRebZScore = as.numeric(scale(OffRebAvg, center = TRUE, scale = TRUE)) * -1,
    TotalZscore = FGzscore + RebZscore + OppZscore + OppRebZScore
  )  

```


```{r}
teamzscore |> arrange(desc(TotalZscore))
```

```{r}
teamzscore |> 
  filter(Conference == "Big Ten WBB") |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)
```


```{r}

powerfive_plus_one <- c("SEC WBB", "Big Ten WBB", "Pac-12 WBB", "Big 12 WBB", "ACC WBB", "Big East WBB")
teamzscore |> 
  filter(Conference %in% powerfive_plus_one) |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)

```


--------------------------
###SRS In-class activity

```{r}

teams <- read_csv("https://dwillis.github.io/sports-data-files/wbbstats25.csv")

```
```{r}

library(ggrepel)

umd <- teams |>
  filter(School == "Maryland")

unbeaten <- teams |>
  filter(OverallLosses == 0)

big_ten <- teams |> filter(School %in% c('Illinois', 'Indiana', 'Iowa', 'Michigan', 'Michigan State', 'Ohio State', 'Minnesota', 'Nebraska', 'Northwestern', 'Rutgers', 'Southern California', 'UCLA', 'Oregon', 'Washington', 'Maryland'))


avg_srs <- unbeaten |>
  filter(!is.na(OverallSRS)) |>
  summarise(mean(OverallSRS)) |>
  pull(1)

avg_sos <- unbeaten |>
  filter(!is.na(OverallSOS)) |>
  summarise(mean(OverallSOS)) |>
  pull(1)

ggplot() +
  geom_point(data = unbeaten, aes(x=OverallSRS, y= OverallSOS, size = OverallWins), color = "grey") +
  geom_point(data = big_ten, aes(x=OverallSRS, y= OverallSOS, size = OverallWins), color = "yellow") +
  geom_point(data = umd, aes(x=OverallSRS, y= OverallSOS, size = OverallWins), color = "red") +
  geom_vline(xintercept = avg_srs) +
  geom_hline(yintercept = avg_sos) +
  geom_text_repel(
    data=big_ten, 
    aes(x=OverallSRS, y=OverallSOS, label=School)
  )

```












